# Generated by Django 2.2 on 2021-05-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='status',
            field=models.CharField(choices=[('private', 'приватный'), ('public', 'публичный')], default='public', max_length=50, verbose_name='статус'),
        ),
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('private', 'приватный'), ('public', 'публичный')], default='public', max_length=50, verbose_name='статус'),
        ),
    ]
