# Generated by Django 2.2 on 2021-05-29 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_auto_20210529_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PhotoUser', to='webapp.Photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PhotoUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранное(фото)',
                'verbose_name_plural': 'Избранные(фото)',
            },
        ),
        migrations.CreateModel(
            name='AlbumUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AlbumUser', to='webapp.Album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AlbumUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранное(альбом)',
                'verbose_name_plural': 'Избранные(альбом)',
            },
        ),
    ]
