# Generated by Django 2.2 on 2021-05-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_albumuser_photouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='status',
            field=models.CharField(choices=[('private', 'приватный'), ('public', 'публичный')], default='new', max_length=50, verbose_name='статус'),
        ),
    ]
