# Generated by Django 2.2 on 2021-05-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210529_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='status',
            field=models.CharField(choices=[('private', 'приватный'), ('public', 'публичный')], default='public', max_length=50, verbose_name='статус'),
        ),
    ]
